# Generated by Django 6.1.1 on 2026-09-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Property Owner')], default='tenant', max_length=20, verbose_name='Account Role'),
        ),
    ]
