# Generated by Django 6.1.1 on 2026-09-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Property Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('studio', 'Studio'), ('condo', 'Condominium'), ('commercial', 'Commercial Space')], default='apartment', max_length=50, verbose_name='Property Type')),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Rent ($)')),
                ('location', models.CharField(max_length=255, verbose_name='Location / Address')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Bathrooms')),
                ('area_sqft', models.PositiveIntegerField(blank=True, null=True, verbose_name='Area (sq ft)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/', verbose_name='Property Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available for Rent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_date', models.DateField(verbose_name='Desired Move-In Date')),
                ('lease_duration_months', models.PositiveIntegerField(default=12, verbose_name='Lease Duration (Months)')),
                ('message', models.TextField(blank=True, verbose_name='Message / Introduction to Owner')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Request Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
