# Generated by Django 6.1.1 on 2026-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='e.g. Central AC, Balcony, In-unit Laundry, Private Yard, Dishwasher', verbose_name='House Amenities & Features'),
        ),
        migrations.AddField(
            model_name='property',
            name='furnished_status',
            field=models.CharField(choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('furnished', 'Fully Furnished')], default='unfurnished', max_length=30, verbose_name='Furnishing Status'),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_info',
            field=models.CharField(blank=True, help_text='e.g. 2 Garage Spaces, Driveway, Street', max_length=120, verbose_name='Parking Information'),
        ),
        migrations.AddField(
            model_name='property',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet Friendly'),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Security Deposit ($)'),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities_included',
            field=models.CharField(blank=True, help_text='e.g. Water, Gas, Trash, WiFi', max_length=255, verbose_name='Utilities Included'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Year Built'),
        ),
    ]
