# Generated by Django 6.1.1 on 2026-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_amenities_property_furnished_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='furnished_status',
            field=models.CharField(blank=True, choices=[('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished'), ('furnished', 'Fully Furnished')], default='unfurnished', max_length=30, verbose_name='Furnishing Status'),
        ),
    ]
